### PR TITLE
🧹 chore (App Frontend): Make sure cross-scripting is not possible through github changelog entries

### PR DESCRIPTION
**Pull request by TadeSF**
branch: changelog-prevent-cross-scripting

@m1212e please have a look at this.
Github itself takes x-scripting very seriously, so i don't think it is even possible to add scripts to changelogs, since the markdown content is always sanatized. But with this plugin in place, we should be absolutely on the safe side. This sanitizes by default to the Github Standards, which should fit perfectly. We should test his though, and I also did not spend too much time on the research, so please feel free to have a second thorough look.

### CODE REVIEW

**Comment by m1212e** [comment]
Yeah I think since first of all github and then out frontend checks for injections we should be good. Nice find, didn't know about this before!

**Review by m1212e — APPROVED** [review]

**Comment by m1212e** [comment]
As you mentioned we coudl/should do some testing before merging

**Comment by TadeSF** [comment]
Then this would be the perfect opportunity to establish the nightly branch, wouldn't it? :D
Otherwise I would need to merge to test (or make a release from this branch, but I don't like that approach)

**Comment by m1212e** [comment]
Indeed, I'll create one and the related actions

**Comment by m1212e** [comment]
Please see https://github.com/DeutscheModelUnitedNations/munify/pull/190

**Pull request closed without merging**
